version: "3.7"
services:

    portfolio-frontend:
        build: .
        image: portfolio-frontend:latest
        ports:
            - 3000:3000
        volumes:
            - .:/frontend
        environment:
            HOST: 0.0.0.0
        container_name: portfolio-frontend