name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    
    - run: npm install nuxt
    - run: npm run generate:gh-pages
    
    - name: GitHub Pages Deployment
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        publish_dir: dist
        user_name: elpapi42
        user_email: whitman-2@hotmail.com
        commit_message: Deploy to Github Pages
